Description: >
  This template illustrates the demo architecture for a Blue/Green Deployment on ECS using the "itsacat" Prediction API.

Parameters:
  GitHubUser:
    Type: String
    Description: GitHub username.

  GitHubRepo:
    Type: String
    Default: itsacat-local
    Description: The repo name of the Prediction API.
    AllowedPattern: "[A-Za-z0-9_.-]*"
    MaxLength: 50

  GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to continuously deploy.

  GitHubToken:
    Type: String
    Description: >
      Token for the user specified above. (https://github.com/settings/tokens)

  TemplateBucket:
    Type: String
    Description: S3 Bucket used for nested templates.
  
  EmailAddress:
    Description: Email Address for Approval.
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal Access Token"
      TemplateBucket:
        default: "Template Bucket"
      EmailAddress:
        default: "Email Address"
    ParameterGroups:
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken
      - Label:
          default: Machine Learning Pipline Configuration
        Parameters:
          - TemplateBucket
          - EmailAddress

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.215.0.0/16
        PublicSubnet1CIDR: 10.215.10.0/24
        PublicSubnet2CIDR: 10.215.11.0/24

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/deployment-pipeline.yaml
      Parameters:
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        TemplateBucket: !Ref TemplateBucket
        Subnet1: !GetAtt VPC.Outputs.PublicSubnet1
        Subnet2: !GetAtt VPC.Outputs.PublicSubnet2
        VpcId: !GetAtt VPC.Outputs.VPC
        VpcCIDR: 10.215.0.0/16
        EmailAddress: !Ref EmailAddress

Outputs:
  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl