AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Description: Optimizes a Neural Network for Image Classification and provides the paramaters to CodeDeploy

Resources:
  Trainer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: trainer.lambda_handler
      Runtime: python3.6
      # Local Package for testing
      CodeUri: package.zip
      # S3 Bucket for production
#      CodeUri: s3://itsacat-local/package.zip
      MemorySize: 3008
      Timeout: 300
      Events:
        S3CreateObject:
          Type: S3
          Properties:
            Bucket: !Ref TrainingInputBucket
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: 'h5'

  TrainingInputBucket:
    Type: AWS::S3::Bucket
