AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Description: Optimizes a Neural Network for Image Classification and provides the paramaters to CodeDeploy

Resources:
  Demo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: trainer.lambda_handler
      Runtime: python3.6
      CodeUri: package.zip
      MemorySize: 3008
      Timeout: 300
      Events:
        S3CreateObject:
          Type: S3
          Properties:
            Bucket: !Ref TrainingInputBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: 'h5'
      Policies:
        - AmazonS3FullAccess

  TrainingInputBucket:
    Type: AWS::S3::Bucket
